"""Initial migration

Revision ID: 9fbea3ec0163
Revises: 
Create Date: 2025-01-22 22:21:55.067655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9fbea3ec0163'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('parent_id', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['parent_id'], ['activities.id'], ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('buildings',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('address', sa.String(), nullable=False),
                    sa.Column('latitude', sa.Float(), nullable=False),
                    sa.Column('longitude', sa.Float(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('organizations',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('building_id', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('organization_activity',
                    sa.Column('organization_id', sa.Integer(), nullable=False),
                    sa.Column('activity_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('organization_id', 'activity_id')
                    )
    op.create_table('phones',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('number', sa.String(), nullable=False),
                    sa.Column('organization_id', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phones')
    op.drop_table('organization_activity')
    op.drop_table('organizations')
    op.drop_table('buildings')
    op.drop_table('activities')
    # ### end Alembic commands ###
